listaa = []
listaa.append('x')
print(listaa)
listaa.append('w')
listaa.append('k')
print(listaa)
listaa.pop()
print(listaa)
listaa.pop()
print(listaa)
listaa.append('w')
listaa.append('k')
listaa.append('y')
listaa.append('z')
print(listaa)